CREATE TABLE USERS(
	U_ID VARCHAR2(60) PRIMARY KEY,
	U_PWD VARCHAR2(256) NOT NULL,
	U_PNUM VARCHAR2(20),
	U_GENDER VARCHAR2(20),
	U_BIRTH DATE,
	U_NUM VARCHAR2(256),
	U_REGDATE DATE DEFAULT sysdate,
	U_ROLE VARCHAR(20)DEFAULT 'ROLE_USER',
	U_POINT NUMBER DEFAULT 0 CHECK(U_POINT > -1),
	U_MSGNUM NUMBER DEFAULT 5 CHECK(U_MSGNUM < 6 AND U_MSGNUM > -1),
	U_SERNUM NUMBER	DEFAULT 5 CHECK(U_SERNUM < 6 AND U_SERNUM > -1),
	U_MSGITEM NUMBER DEFAULT 0 CHECK(U_MSGITEM > -1),
	U_KEYITEM NUMBER DEFAULT 0 CHECK(U_KEYITEM > -1),
	U_SERITEM NUMBER DEFAULT 0 CHECK(U_SERITEM > -1),
	U_MSGACTIVE NUMBER DEFAULT 1,
	U_ACTIVE NUMBER	DEFAULT 0
);